version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: npm run dev
